import React from 'react';
import { ToolCall } from '../types';
import { ImageIcon } from './icons/ImageIcon';

export const ImageResultCard: React.FC<{ toolCall: ToolCall }> = ({ toolCall }) => {
  const { status, result, error } = toolCall;

  if (status === 'pending') {
     return (
        <div className="mt-2 p-3 rounded-lg w-full max-w-sm md:max-w-md border bg-blue-50 dark:bg-gray-800 border-blue-200 dark:border-gray-700">
            <div className="flex items-center gap-2">
                <div className="w-4 h-4 border-2 border-slate-400 border-t-transparent rounded-full animate-spin"></div>
                <span className="text-sm italic text-gray-600 dark:text-gray-400">Generating image...</span>
            </div>
        </div>
     );
  }
  
  if (error) {
     return (
        <div className="mt-2 p-3 rounded-lg w-full max-w-sm md:max-w-md border bg-red-50 dark:bg-red-900/40 border-red-200 dark:border-red-700/60">
             <div className="flex items-center gap-2 mb-2">
                <ImageIcon className="h-5 w-5 text-gray-600 dark:text-gray-400" />
                <span className="text-sm font-semibold text-gray-700 dark:text-gray-300">Image Generation</span>
            </div>
            <p className="text-sm text-red-800 dark:text-red-300">{error}</p>
        </div>
     );
  }

  if (typeof result !== 'string') {
    return null;
  }

  return (
    <div className="mt-2 p-2 rounded-lg w-full max-w-sm md:max-w-md border bg-green-50 dark:bg-gray-800 border-green-200 dark:border-gray-700">
        <div className="flex items-center gap-2 mb-2 px-1">
            <ImageIcon className="h-5 w-5 text-gray-600 dark:text-gray-400" />
            <span className="text-sm font-semibold text-gray-700 dark:text-gray-300">Generated Image</span>
        </div>
        <img 
            src={`data:image/jpeg;base64,${result}`} 
            alt="Generated by AI" 
            className="rounded-md w-full object-contain"
        />
    </div>
  );
};
