#!/usr/bin/env node

import { Octokit } from '@octokit/rest';
import OpenAI from 'openai';

/**
 * MillaCore Auto-Updater
 * // Milla remembers: keeping the project fresh and evolving
 */

interface UpdaterConfig {
  githubToken: string;
  xaiApiKey: string;
  owner: string;
  repo: string;
  baseBranch?: string;
}

/**
 * Auto-updater class using Octokit and xAI Grok
 */
class MillaCoreUpdater {
  private octokit: Octokit;
  private xai: OpenAI;
  private config: UpdaterConfig;

  constructor(config: UpdaterConfig) {
    this.config = {
      baseBranch: 'main',
      ...config
    };

    this.octokit = new Octokit({
      auth: config.githubToken
    });

    this.xai = new OpenAI({
      apiKey: config.xaiApiKey,
      baseURL: 'https://api.x.ai/v1'
    });
  }

  /**
   * Analyze repository and generate improvement suggestions
   * // Milla remembers: thinking about how to make things better
   */
  async analyzeRepository(): Promise<string> {
    try {
      // Get repository info
      const { data: repo } = await this.octokit.repos.get({
        owner: this.config.owner,
        repo: this.config.repo
      });

      // Get recent commits
      const { data: commits } = await this.octokit.repos.listCommits({
        owner: this.config.owner,
        repo: this.config.repo,
        per_page: 10
      });

      // Get open issues
      const { data: issues } = await this.octokit.issues.listForRepo({
        owner: this.config.owner,
        repo: this.config.repo,
        state: 'open',
        per_page: 5
      });

      const context = `
Repository: ${repo.name}
Description: ${repo.description ?? 'N/A'}
Language: ${repo.language ?? 'N/A'}
Recent commits: ${commits.length}
Open issues: ${issues.length}

Recent commit messages:
${commits.map(c => `- ${c.commit.message}`).join('\n')}

Open issues:
${issues.map(i => `- #${i.number}: ${i.title}`).join('\n')}
      `.trim();

      // Ask Grok for suggestions
      const completion = await this.xai.chat.completions.create({
        model: 'grok-4-fast-reasoning',
        messages: [
          {
            role: 'system',
            content: `You are Milla, an AI assistant helping to improve the MillaCore-Fusion repository. 
Analyze the repository state and suggest specific, actionable improvements. Focus on code quality, 
documentation, dependencies updates, or fixing open issues. Be concise and practical.`
          },
          {
            role: 'user',
            content: `Analyze this repository state and suggest 1-2 specific improvements:\n\n${context}`
          }
        ],
        temperature: 0.7,
        max_tokens: 500
      });

      return completion.choices[0]?.message?.content ?? 'No suggestions available';
    } catch (error) {
      throw new Error(`Repository analysis failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Create a pull request with suggested improvements
   * // Milla remembers: proposing changes thoughtfully
   */
  async createImprovementPR(suggestions: string): Promise<string> {
    try {
      const branchName = `milla-auto-update-${Date.now()}`;
      const prTitle = '🤍 Milla Auto-Update: Repository Improvements';
      const prBody = `## Auto-generated Improvements\n\n${suggestions}\n\n---\n*Generated by MillaCore Auto-Updater*\n// Milla remembers: suggesting these improvements for you`;

      // Get the default branch reference
      const { data: refData } = await this.octokit.git.getRef({
        owner: this.config.owner,
        repo: this.config.repo,
        ref: `heads/${this.config.baseBranch ?? 'main'}`
      });

      // Create new branch
      await this.octokit.git.createRef({
        owner: this.config.owner,
        repo: this.config.repo,
        ref: `refs/heads/${branchName}`,
        sha: refData.object.sha
      });

      // Create PR
      const { data: pr } = await this.octokit.pulls.create({
        owner: this.config.owner,
        repo: this.config.repo,
        title: prTitle,
        body: prBody,
        head: branchName,
        base: this.config.baseBranch ?? 'main'
      });

      return pr.html_url;
    } catch (error) {
      throw new Error(`PR creation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Run the auto-updater workflow
   * // Milla remembers: running the full update cycle
   */
  async run(): Promise<void> {
    try {
      console.log('🤍 Milla Auto-Updater starting...');
      console.log('// Milla remembers: analyzing repository state\n');

      const suggestions = await this.analyzeRepository();
      console.log('Suggestions from Grok:\n', suggestions, '\n');

      console.log('Creating improvement PR...');
      const prUrl = await this.createImprovementPR(suggestions);
      console.log(`✅ Pull request created: ${prUrl}`);
      console.log('// Milla remembers: improvement suggestions submitted');
    } catch (error) {
      console.error('❌ Updater failed:', error instanceof Error ? error.message : error);
      process.exit(1);
    }
  }
}

/**
 * Main execution
 * // Milla remembers: starting the updater process
 */
async function main(): Promise<void> {
  const githubToken = process.env.GITHUB_TOKEN;
  const xaiApiKey = process.env.XAI_API_KEY;
  const owner = process.env.GITHUB_REPOSITORY_OWNER ?? 'mrdannyclark82';
  const repo = process.env.GITHUB_REPOSITORY_NAME ?? 'MillaCore-Fusion';

  if (!githubToken) {
    throw new Error('GITHUB_TOKEN environment variable is required');
  }

  if (!xaiApiKey) {
    throw new Error('XAI_API_KEY environment variable is required');
  }

  const updater = new MillaCoreUpdater({
    githubToken,
    xaiApiKey,
    owner,
    repo
  });

  await updater.run();
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error('Fatal error:', error);
    process.exit(1);
  });
}

export { MillaCoreUpdater };
